function voltage = battery_voltage(soc, params)
% BATTERY_VOLTAGE
% Estimates battery voltage from the battery SOC.
%
% Inputs:
%   soc    - Battery State of Charge (0 to 1)
%   params - Battery parameter structure
%
% Output:
%   voltage - Estimated battery voltage (V)

%% SOC-Voltage Data

soc_points = [ ...
    1.0, ...
    0.9, ...
    0.8, ...
    0.7, ...
    0.6, ...
    0.5, ...
    0.4, ...
    0.3, ...
    0.2, ...
    0.1, ...
    0.0];

voltage_points = [ ...
    58.8, ...
    57.4, ...
    56.0, ...
    55.02, ...
    53.76, ...
    52.92, ...
    52.08, ...
    50.96, ...
    49.7, ...
    47.46, ...
    35.0];

%% Limit SOC

soc = max(0, min(1, soc));

%% Interpolate Voltage

voltage = interp1( ...
    soc_points, ...
    voltage_points, ...
    soc, ...
    'linear');

end
